spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  data:
    mongodb:
      uri: mongodb://10.10.1.106/security_demo
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write_dates_as_timestamps: false
  freemarker: 
    enabled: true
    template-loader-path: classpath:/view/
    suffix: .html
    charset: UTF-8
    time_format: HH:mm:ss
    check-template-location: true
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    #allow-session-override: true
    #allow-request-override: true
    settings: 
      auto_include: common/template.html
  mvc:
    locale: zh_CN
    date-format: yyyy-MM-dd
server:
  port: 8080
  session:
    cookie:
      http-only: true